name: Atualizar Dados ANS

on:
  schedule:
    - cron: '0 0 * * 1' # Roda toda segunda-feira à meia-noite
  workflow_dispatch: # Permite rodar manualmente clicando em um botão

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: pip install pandas requests

      - name: Executar Processamento Odonto
        run: python process_ans.py

      - name: Executar Processamento Medico
        run: python process_medico.py

      - name: Commit e Push de ambos
        run: |
          git add dados_odonto.json dados_medico.json
          git commit -m "Update: Dados Medico e Odonto [skip ci]" || exit 0
          git push
